'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Resources")>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SPARX_Management_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ActiveInstallation() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("ActiveInstallation", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property billing() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("billing", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BLueWrench() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("BLueWrench", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlueDot() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("BlueDot", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtercupDot() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("ButtercupDot", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dashboard() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("dashboard", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("delete", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EcstacyDot() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("EcstacyDot", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("edit", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eye_open() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("eye_open", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eye_slashed() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("eye_slashed", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("filter", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greenCompleted() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("greenCompleted", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greenDot() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("greenDot", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GreenPeso() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("GreenPeso", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GreenWifi() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("GreenWifi", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("history", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property installation() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("installation", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventory() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("inventory", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MonthlyRevenue() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("MonthlyRevenue", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property networkMap() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("networkMap", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notificationBell() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("notificationBell", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property orangePending() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("orangePending", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OrangeBlocked() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("OrangeBlocked", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payroll() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("payroll", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PendingServices() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("PendingServices", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plan() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("plan", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pnlShadow() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("pnlShadow", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pnlShadow1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("pnlShadow1", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redDot() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("redDot", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redInProgress() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("redInProgress", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedDanger() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("RedDanger", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sales() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("sales", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property service() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("service", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SparxBackground() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("SparxBackground", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SparxFiber() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("SparxFiber", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SparxLogo1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("SparxLogo1", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SparxLogo2() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("SparxLogo2", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property subscriber() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("subscriber", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TotalSusbcribers() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("TotalSusbcribers", resourceCulture), System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace

